use_frameworks!

platform :ios, '14.0'

target 'ios-printer-toshiba_Example' do
  pod 'ios-printer-toshiba/Device', :path => '../'
  #pod 'ios-printer-toshiba/Simulator', :path => '../'

  target 'ios-printer-toshiba_Tests' do
    inherit! :search_paths

    
  end
end
